name: wildalert
channels:
  - pytorch
  - conda-forge
  - huggingface
dependencies:
  - python=3.11
  - pip
  - jupyterlab
  - pip:
      - accelerate==0.24.0
      - datasets==2.14.6
      - fastapi>=0.104.1
      - matplotlib
      - seaborn
      - pre-commit
      - rich
      - scikit-learn==1.3.2
      - tokenizers==0.14.1
      - transformers==4.34.1
      - uvicorn>=0.24.0
